optimize catch error logic

diff --git a/.github/workflows/Sign image (avbtool).yml b/.github/workflows/Sign image (avbtool).yml
--- a/.github/workflows/Sign image (avbtool).yml
+++ b/.github/workflows/Sign image (avbtool).yml
@@ -72,7 +72,7 @@ jobs:
           rm -v rsa4096_${{ github.event.inputs.TARGET }}_pub.bin
           cp -v rsa4096_custom_pub.bin rsa4096_${{ github.event.inputs.TARGET }}_pub.bin
           ./sign_vbmeta.sh
-          if [ ! '${{ github.event.inputs.VER }}' == 'vbmeta has no DHTB header, no need for padding' ];then python vbmeta_pad_${{ github.event.inputs.VER }}_$(cat sign_vbmeta.sh |grep padding |cut -d' ' -f 2).py; fi || if [ $? == 2 ]; then echo 'Failed to find padding script, did you choose correct Android version? stopping...'&&exit 1; fi
+          if [ ! '${{ github.event.inputs.VER }}' == 'vbmeta has no DHTB header, no need for padding' ];then python vbmeta_pad_${{ github.event.inputs.VER }}_$(cat sign_vbmeta.sh |grep padding |cut -d' ' -f 2).py; fi || if [ $? == 2 ]; then echo 'Failed to find padding script, did you choose correct Android version? stopping...'&&exit 127; else echo 'Error, stopping'&&exit 1; fi
           echo "VBMeta signed!"
           echo "Signing your ${{ github.event.inputs.TARGET }} image..."
           python avbtool add_hash_footer --image ${{ github.event.inputs.TARGET }}.img --partition_name ${{ github.event.inputs.TARGET }} --partition_size ${{ github.event.inputs.SIZE }} --key rsa4096_vbmeta.pem --algorithm SHA256_RSA4096
